# Generated by Django 4.2.6 on 2023-10-09 11:53

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='system_response_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='system_response',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
