# Generated by Django 4.2.6 on 2023-10-09 12:04

from django.db import migrations, models
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chathistory_system_response_rendered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='system_response_2',
            field=markdownfield.models.MarkdownField(default=1, rendered_field='text_rendered', use_editor=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chathistory',
            name='system_response',
            field=models.TextField(),
        ),
    ]
