# Generated by Django 4.2.6 on 2023-10-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chathistory_system_response_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='system_response',
            field=models.JSONField(null=True),
        ),
    ]
