# Generated by Django 4.2.6 on 2023-10-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_chathistory_system_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='system_response',
            field=models.JSONField(null=True),
        ),
    ]
