# Generated by Django 4.2.6 on 2023-10-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_chathistory_system_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='system_response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
